services:
  mysql_src_db:
    image: mysql:8.1
    container_name: mysql_src_db
    restart: unless-stopped
    ports:
      - "3306:3306"       # Host port 3306 maps to container's 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1
      MYSQL_DATABASE: db_src
      MYSQL_USER: devuser1
      MYSQL_PASSWORD: devpass1
    volumes:
      - mysql_src_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_warehouse_db:
    image: postgres:16-alpine
    container_name: postgres_warehouse_db
    restart: unless-stopped
    ports:
      - "5433:5432"       # Host port 5433 maps to container's 5432
    environment:
      POSTGRES_DB: db_warehouse
      POSTGRES_USER: devuser2
      POSTGRES_PASSWORD: devpass2
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_warehouse_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser2 -d db_warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  mysql_src_data:
  postgres_warehouse_data:
