"""added indexes for real this time

Revision ID: 17cb9b827137
Revises: 1d4d9a2a94ec
Create Date: 2025-10-12 11:34:26.984196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cb9b827137'
down_revision: Union[str, Sequence[str], None] = '1d4d9a2a94ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_quareter', 'dim_date', ['Quarter'], unique=False)
    op.create_index('idx_yq', 'dim_date', ['Year', 'Quarter'], unique=False)
    op.create_index('idx_yqm', 'dim_date', ['Year', 'Quarter', 'Month'], unique=False)
    op.create_index('idx_category', 'dim_products', ['Category'], unique=False)
    op.create_index('idx_product_name', 'dim_products', ['Name'], unique=False)
    op.create_index('idx_city', 'dim_users', ['City'], unique=False)
    op.create_index('idx_country', 'dim_users', ['Country'], unique=False)
    op.create_index('idx_fact_fk', 'fact_order_items', ['Product_ID', 'User_ID', 'Delivery_Date_ID', 'Total_Revenue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_fk', table_name='fact_order_items')
    op.drop_index('idx_country', table_name='dim_users')
    op.drop_index('idx_city', table_name='dim_users')
    op.drop_index('idx_product_name', table_name='dim_products')
    op.drop_index('idx_category', table_name='dim_products')
    op.drop_index('idx_yqm', table_name='dim_date')
    op.drop_index('idx_yq', table_name='dim_date')
    op.drop_index('idx_quareter', table_name='dim_date')
    # ### end Alembic commands ###
