"""removed unused columns in user table

Revision ID: 208f8b938be4
Revises: ef013a62618a
Create Date: 2025-10-12 15:12:43.264525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '208f8b938be4'
down_revision: Union[str, Sequence[str], None] = 'ef013a62618a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_users', 'Address_1')
    op.drop_column('dim_users', 'Address_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_users', sa.Column('Address_2', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('dim_users', sa.Column('Address_1', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
