"""composite index delivery date and revenue

Revision ID: 69366783bc04
Revises: 17cb9b827137
Create Date: 2025-10-12 11:44:09.664768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69366783bc04'
down_revision: Union[str, Sequence[str], None] = '17cb9b827137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_date_revenue', 'fact_order_items', ['Delivery_Date_ID', 'Total_Revenue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_date_revenue', table_name='fact_order_items')
    # ### end Alembic commands ###
