"""fixed typo on dim date index

Revision ID: 7fca2bf29c2e
Revises: 856d5c9de418
Create Date: 2025-10-12 12:01:15.135845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fca2bf29c2e'
down_revision: Union[str, Sequence[str], None] = '856d5c9de418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_quareter'), table_name='dim_date')
    op.create_index('idx_quarter', 'dim_date', ['Quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quarter', table_name='dim_date')
    op.create_index(op.f('idx_quareter'), 'dim_date', ['Quarter'], unique=False)
    # ### end Alembic commands ###
