"""fixed typo on the rider indexes

Revision ID: 856d5c9de418
Revises: df66081799b1
Create Date: 2025-10-12 11:52:14.360582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856d5c9de418'
down_revision: Union[str, Sequence[str], None] = 'df66081799b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rider_groupby', 'dim_riders', ['Courier_Name', 'Vehicle_Type', 'First_Name', 'Last_Name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rider_groupby', table_name='dim_riders')
    # ### end Alembic commands ###
