"""removed auto increment from fact table2

Revision ID: b4976bc3c720
Revises: 8e23a5b1d55b
Create Date: 2025-10-13 20:43:54.479337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4976bc3c720'
down_revision: Union[str, Sequence[str], None] = '8e23a5b1d55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
