"""removed redundant index

Revision ID: c492bb9a7554
Revises: 7fca2bf29c2e
Create Date: 2025-10-12 13:24:41.668896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c492bb9a7554'
down_revision: Union[str, Sequence[str], None] = '7fca2bf29c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_quarter'), table_name='dim_date')
    op.drop_index(op.f('idx_yq'), table_name='dim_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_yq'), 'dim_date', ['Year', 'Quarter'], unique=False)
    op.create_index(op.f('idx_quarter'), 'dim_date', ['Quarter'], unique=False)
    # ### end Alembic commands ###
