"""composite index rider and revenue

Revision ID: df66081799b1
Revises: 69366783bc04
Create Date: 2025-10-12 11:47:11.432031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df66081799b1'
down_revision: Union[str, Sequence[str], None] = '69366783bc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rider_revenue', 'fact_order_items', ['Delivery_Rider_ID', 'Total_Revenue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rider_revenue', table_name='fact_order_items')
    # ### end Alembic commands ###
