"""remove not used columns in user table

Revision ID: ef013a62618a
Revises: c492bb9a7554
Create Date: 2025-10-12 14:19:55.628206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef013a62618a'
down_revision: Union[str, Sequence[str], None] = 'c492bb9a7554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_users', 'Phone_Number')
    op.drop_column('dim_users', 'Birth_Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_users', sa.Column('Birth_Date', sa.DATE(), nullable=False))
    op.add_column('dim_users', sa.Column('Phone_Number', mysql.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
